spring:
  profiles:
    active: local
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    config:
      enabled: false
  data:
    web:
      pageable:
        one-indexed-parameters: false
  main:
    allow-bean-definition-overriding: true
#  redis:
#    password: steve123!
#    database: 0
#    host: 47.99.152.254
#    port: 6379
#    jedis:
#      pool:
#        max-active: 8
#        max-wait: 1
#        max-idle: 8
#        min-idle: 0
#    timeout: 3000

server:
  port: 8080
  undertow:
    io-threads: 4
    worker-threads: 20
    buffer-size: 1024
    direct-buffers: true
logging:
  level:
    root: info
    org:
      springframework:
        web: warn
eureka:
  instance:
    hostname: localhost
  client:
    eureka-server-port: 8400
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${eureka.client.eureka-server-port}/eureka/
    register-with-eureka: false
    fetch-registry: true

ribbon:
  eureka:
    enabled: true
AuthWebService:
  ribbon:
    listOfService: http://localhost:8401
ChatWebService:
  ribbon:
    listOfService: http://localhost:8401